// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Cotrap.Core.Interfacce;
using System;
using System.Collections.Generic;

namespace Cotrap.Data.Northwind.Models;

public partial class Category: IEntity<int>
{
    public int Id { get; set; }
    // public int CategoryId { get; set; }

    public string CategoryName { get; set; }

    public string Description { get; set; }

    public byte[] Picture { get; set; }

    public virtual ICollection<Product> Products { get; set; } = new List<Product>();
    
}